version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    env_file: .env
    command: /bin/sh -c "/scripts/runserver.sh"
    volumes:
      - ./src:/code
    ports:
      - "${APP_PORT}:${PORT}"