version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
        - checkout

        - setup_remote_docker:
            docker_layer_caching: false

        - run:
            name: Setup Stage
            command: |
                if [ $CIRCLE_BRANCH == "dev" ]
                then
                    echo 'export STAGE=development' >> ~/.bashrc
                    echo 'export APP_NAME=dev-kooora' >> ~/.bashrc
                elif [ $CIRCLE_BRANCH == "master" ]
                then
                    echo 'export STAGE=production' >> ~/.bashrc
                    echo 'export APP_NAME=kooora' >> ~/.bashrc
                else
                    echo "No stage provided!"
                fi

        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                cd src
                pip install -r requirements.txt

        - run:
            name: run tests
            command: |
                . venv/bin/activate
                python3 manage.py migrate
                python3 manage.py test
                
        - run:
            name: "Heroku Install"
            command: |
                if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
                else
                echo "Heroku already exists!"
                fi
    
        - run:
            name: Login into Heroku Docker Repository
            command: |
                docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
        - run:
            name: Deploy Heroku Docker Container
            command: |
                heroku container:push web -a $APP_NAME
                heroku container:release web -a $APP_NAME